### ISSUE TITLE
וידוא מספר שולחן פנוי - נתי

### ISSUE THREAD

**Issue by NetanelAlbert** [NetanelAlbert/PayEat#103]
https://github.com/NetanelAlbert/PayEat/blob/858e6d5a37aee6326e9d57628cc5e6e59a024b63/app/src/main/java/com/example/payeat/activities/MainActivity.java#L64

**Comment by ido1Shapira** [comment]
החלטנו לוותר על בדיקה של שולחן פנוי ולכן נסגר
