### ISSUE TITLE
שיכפול מיותר בדאטה בייס

### ISSUE THREAD

**Issue by NetanelAlbert** [NetanelAlbert/PayEat#115]
כאשר שומרים מנה ב"הזמנות חיות" היא משתכפלת במקום שנצביע למספר מזהה שלה

**Comment by ido1Shapira** [comment]
למה זה לא יכול להשאר ככה ?

**Comment by edutco** [comment]
הוחלט שישאר כך מאחר ויתכנו שינויים ספציפים בהזמנה של שולחן מסויים ולכן לא ניתן לשאוב את המידע מהתפריט בלבד
