### ISSUE TITLE
הזמינו חשבון

### ISSUE THREAD

**Issue by ido1Shapira** [NetanelAlbert/PayEat#124]
להוסיף אופציה למנהל אפשרות למחוק הזמנות מענף הביקשו חשבון לשולחנות שהגיעו לשלב זה

OnItemClick()

**Comment by ido1Shapira** [comment]
ברגע שהמנהל ימחק זה יעבור לענף חדש שנקרא: 

הסטוריית הזמנות

שאחכ
נשאב משם סטטיסטיקות

**Comment by edutco** [comment]
בוצע
